include:
  - project: 'framework/fixers/cicd'
    file: 'make/.gitlab-ci-jdk17.yml'

stages:
  - package

##########################################
## Tasks
##########################################
keycloak-theme:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docker-web

web:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docker-keycloak
