version: "3.7"

services:
  im-gateway:
    image: smartbcity/im-gateway:experimental
    container_name: im-gateway
    environment:
      - i2_issuers[0]_name=local
      - i2_issuers[0]_authUrl=${AUTH_HOST_URL}
      - i2_issuers[0]_realm=im-test
      - i2_issuers[0]_im_clientId=sb-platform-app-im
      - i2_issuers[0]_im_clientSecret=secret
    ports:
      - "8009:8009"

networks:
  bclannet-it:
    name: bclannet-it
    external: true
