version: "3.7"

services:
  i2-init:
    image: smartbcity/i2-init:experimental-13122
    container_name: i2-init
    environment:
      i2_keycloak_serverUrl: ${AUTH_HOST_URL}
      i2_keycloak_username: ${KC_ROOT_USER}
      i2_keycloak_password: ${KC_ROOT_PASS}
      i2_init_realm: ${KC_REALM}
      i2_init_adminUser_username:  ${KC_ADMIN_USER}
      i2_init_adminUser_email: admin@admin.com
      i2_init_adminUser_firstname: admin
      i2_init_adminUser_lastname: admin
      i2_init_adminUser_password: ${KC_ADMIN_PASS}
      i2_init_adminClient_secret: ${KC_ADMIN_CLIENT_SECRET}
      i2_init_adminClient_name: ${KC_ADMIN_CLIENT_ID}
      i2_init_smtp_host: connect-fake-smtp

networks:
  bclannet-it:
    name: bclannet-it
    external: true