version: "3.7"

services:
  keycloak-it:
    image: smartbcity/i2-keycloak:experimental
    container_name: ${KC_HOSTNAME}
    environment:
      KC_DB_URL: 'jdbc:postgresql://keycloak-postgres/keycloak-it'
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_SCHEMA: public
      KC_HOSTNAME: ${KC_HOSTNAME}:8080
      KEYCLOAK_ADMIN: ${KC_ROOT_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ROOT_PASS}
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - '8080:8080'
    depends_on:
      - keycloak-postgres-it
  keycloak-postgres-it:
    image: postgres
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak-it
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  bclannet-it:
    name: bclannet-it
    external: true
