version: "3.7"

services:
  i2-config:
    image: smartbcity/i2-config:${I2_VERSION}
    container_name: i2-config
    environment:
      i2_keycloak_serverUrl: ${AUTH_HOST_URL}
      i2_keycloak_realm: ${KC_REALM}
      i2_keycloak_clientId: ${KC_ADMIN_CLIENT_ID}
      i2_keycloak_clientSecret: ${KC_ADMIN_CLIENT_SECRET}
      i2_config_json: file:/tmp/config.json
    volumes:
      - ./config.json:/tmp/config.json

networks:
  bclannet-it:
    name: bclannet-it
    external: true